//declaração de variáveis e constantes
/*
//let mensagem = 'oi mundo';
console.log(mensagem);
mensagem ='oi';
console.log (mensagem);
//ou
const mensagem = true;
console.log(mensagem);
console.log (typeof(mensagem));


//Funções

  function somar(numA, numB) =>{
    return numA + numB; 
  }

  let resultado = somar(10,10);
  console.log(resultado);

  //Vetores

 // let finalsemana = ['sabado','domingo'];
 // console.log(finalsemana[1])
 // finalsemana.push('sexta feira');
 // console.dir(finalsemana);

 //Objetos

 let agenda = {
    nome: 'harley'
    sobrenome: 'oliveira'
    whatsapp:'(31) 98268-1145';
    return this.nome + '' +this.sobrenome;
 }
 agenda.nome ='wendel';
 agenda.sobrenome = 'santos';
 console.log(agenda.nomecompleto());
  
 //Condicional

 let idade = 21;
 if (idade >= 18){
 console.log('você é maior de idade');

 }
 Else {
     console.log(você é maior de idade);

 }
  //Loop
  let finalsemana = ['sabado','domingo'];
  console.log(finalsemana[0]);
  console.log(finalsemana[1]);
  ou
  finalsemana.forEach(function(dia)){
    console.log('final de semana:' + dia);
  }
  for(let dia of finalsemana){
  console.log(dia);
 //* }